name: publish-book

# Only run this when the jupyterbook branch changes
on:
  workflow_dispatch:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Process files
      run: |
        python ci/process_files.py
        
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build . --all
        
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
